# Generated by Django 3.0.2 on 2020-02-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EHeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etitle', models.CharField(max_length=200)),
                ('eimage', models.URLField(blank=True, null=True)),
                ('eurl', models.TextField()),
            ],
        ),
    ]
