# Generated by Django 3.0.2 on 2020-02-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200301_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheadline',
            old_name='simage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='sheadline',
            old_name='stitle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='sheadline',
            old_name='surl',
            new_name='url',
        ),
    ]
