# Generated by Django 3.0.2 on 2020-03-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_headline_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='eheadline',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
