# Generated by Django 3.0.2 on 2020-03-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_eheadline_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheadline',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
