# Generated by Django 3.0.2 on 2020-03-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_sheadline_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='PHeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField(blank=True, null=True)),
                ('url', models.TextField()),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
